{% set name = "yaqd-zaber" %}
{% set version = "2022.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yaqd-zaber-{{ version }}.tar.gz
  sha256: 4b8972db281adf8c4da6c0557effac254e7aa512b3f62d6ddbb659ebb11dad6d

build:
  entry_points:
    - yaqd-zaber-binary = yaqd_zaber._zaber_binary:ZaberBinary.main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - flit-core >=2,<4
  run:
    - python >=3.7
    - zaber-serial
    - yaqd-core >=2020.06.3

test:
  imports:
    - yaqd_zaber
  commands:
    - pip check
    - yaqd-zaber-binary --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: yaq daemons for hardware from Zaber Technologies
  dev_url: https://gitlab.com/yaq/yaqd-zaber
  license: LGPL-3.0-only
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - untzag
